import Head from 'next/head';
import Popular from '../components/Popular';
import Vegie from '../components/Vegie';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Vegie />

      <Popular />
    </div>
  );
}
